version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: care_iot_broker
    restart: unless-stopped
    ports:
      - "8883:8883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto.acl:/mosquitto/config/mosquitto.acl:ro
      - ../certs:/mosquitto/config/certs:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

volumes:
  mosquitto_data:
  mosquitto_log:
