[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino

; Velocità monitor seriale
monitor_speed = 115200

; Porta di upload (quella che abbiamo sbloccato prima)
upload_port = COM5
monitor_port = COM5 

; Aumenta lo spazio per il codice (Cruciale per BLE + SSL!)
board_build.partitions = huge_app.csv

; Librerie necessarie
lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.21.3